cmake_minimum_required(VERSION 3.25.2)

# Exercise precedence and mode changes without configuring/building Kokkos.
function(check_cpu native arch expected)
    set(SCALUQ_CPU_NATIVE "${native}")
    set(SCALUQ_CPU_ARCH "${arch}")
    include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/ScaluqCPU.cmake")
    if(NOT SCALUQ_CONFIGURED_CPU_ARCH STREQUAL expected)
        message(FATAL_ERROR "Expected '${expected}', got '${SCALUQ_CONFIGURED_CPU_ARCH}'")
    endif()
    foreach(candidate NATIVE HSW SKX ZEN2 ARMV8)
        if(candidate STREQUAL expected)
            if(NOT Kokkos_ARCH_${candidate})
                message(FATAL_ERROR "Expected Kokkos_ARCH_${candidate}=ON")
            endif()
        elseif(Kokkos_ARCH_${candidate})
            message(FATAL_ERROR "Stale Kokkos_ARCH_${candidate}=ON")
        endif()
    endforeach()
endfunction()

# Simulate a reused build tree containing the previous SIMD selection.
set(Kokkos_ARCH_SKX ON CACHE BOOL "" FORCE)
check_cpu(ON "" NATIVE)
check_cpu(ON HSW HSW)
check_cpu(ON SKX SKX)
check_cpu(OFF HSW HSW)
check_cpu(OFF SKX SKX)
check_cpu(OFF "" "")
check_cpu(ON ZEN2 ZEN2)
check_cpu(ON ARMV8 ARMV8)
check_cpu(OFF "" "")
check_cpu(ON "" NATIVE)
