cmake_minimum_required(VERSION 3.25.2)

# Run with: cmake -P tests/cmake/cpu_arch_test.cmake
set(CMAKE_SYSTEM_PROCESSOR x86_64)
if(DEFINED CASE)
    # These cases run in a subprocess because configuration errors are fatal.
    set(SCALUQ_SIMD "${CASE}")
    if(CASE STREQUAL "arm")
        set(CMAKE_SYSTEM_PROCESSOR aarch64)
        set(SCALUQ_SIMD AVX2)
    elseif(CASE STREQUAL "legacy")
        set(SCALUQ_SIMD OFF)
        set(SCALUQ_CPU_NATIVE ON)
    endif()
    include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/ScaluqCPU.cmake")
    return()
endif()

foreach(mode OFF AVX2 AVX512 AVX2 OFF)
    set(SCALUQ_SIMD "${mode}")
    include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/ScaluqCPU.cmake")
    if(mode STREQUAL "OFF")
        if(NOT SCALUQ_CPU_COMPILE_OPTIONS STREQUAL "-mno-bmi2")
            message(FATAL_ERROR "OFF must disable BMI2 on x86-64")
        endif()
    elseif(SCALUQ_CPU_COMPILE_OPTIONS)
        message(FATAL_ERROR "AVX modes must not retain the BMI2 override")
    endif()
    if(mode STREQUAL "AVX2")
        if(NOT Kokkos_ARCH_HSW OR Kokkos_ARCH_SKX)
            message(FATAL_ERROR "AVX2 must select only HSW")
        endif()
    elseif(mode STREQUAL "AVX512")
        if(NOT Kokkos_ARCH_SKX OR Kokkos_ARCH_HSW)
            message(FATAL_ERROR "AVX512 must select only SKX")
        endif()
    elseif(Kokkos_ARCH_HSW OR Kokkos_ARCH_SKX OR SCALUQ_EFFECTIVE_CPU_ARCH)
        message(FATAL_ERROR "OFF must clear the previous SIMD target")
    endif()
endforeach()

set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(SCALUQ_SIMD OFF)
include("${CMAKE_CURRENT_LIST_DIR}/../../cmake/ScaluqCPU.cmake")
if(SCALUQ_CPU_COMPILE_OPTIONS)
    message(FATAL_ERROR "ARM must not receive x86 compiler options")
endif()

foreach(case ON avx2 AUTO arm legacy)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DCASE=${case}" -P "${CMAKE_CURRENT_LIST_FILE}"
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT error MATCHES "SCALUQ_SIMD")
        message(FATAL_ERROR "Expected an actionable configuration error for ${case}: ${output}${error}")
    endif()
endforeach()
