version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: tutorials/source/conf.py

python:
  version: 3.12
  install:
    - requirements: tutorials/requirements.txt
    - method: pip
      path: .
