version: 2
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  commands:
    - python doc/source/copy_stub.py

sphinx:
  configuration: doc/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
