# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev2+g90f5f24.d20230602'
__version_tuple__ = version_tuple = (0, 1, 'dev2', 'g90f5f24.d20230602')
