#!/bin/sh

set -eux

GXX_COMMAND=${CXX_COMPILER:-"g++"}

QULACS_USE_OMP=${QULACS_USE_OMP:-"ON"}
QULACS_USE_CUDA=${QULACS_USE_CUDA:-"OFF"}
QULACS_USE_TEST=${QULACS_USE_TEST:-"ON"}
QULACS_USE_EXE=${QULACS_USE_EXE:-"ON"}

CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:-"Release"}

CMAKE_OPS="-D CMAKE_CXX_COMPILER=${GXX_COMMAND} \
  -D CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} \
  -D QULACS_USE_OMP=${QULACS_USE_OMP} \
  -D QULACS_USE_CUDA=${QULACS_USE_CUDA} \
  -D QULACS_USE_TEST=${QULACS_USE_TEST}"

mkdir -p ./build
cmake -B build -G Ninja ${CMAKE_OPS}
ninja -C build -j $(nproc)
