name: Clang-tidy

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-changed:
    name: Check Changed Files
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-24.04
    outputs:
      any_changed: ${{ steps.check.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Check relevant files
        id: check
        uses: tj-actions/changed-files@v47.0.1
        with:
          files: |
            include/**
            src/**

  check-tidy:
    name: Check Format
    needs: [check-changed]
    if: ${{ !cancelled() && (needs.check-changed.result == 'skipped' || needs.check-changed.outputs.any_changed == 'true') }}
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y ninja-build libomp-dev

      - name: Configure
        run: |
          script/configure_tidy

      - name: Run clang-tidy
        run: |
          ninja -C build-tidy clang-tidy

  tidy-check-passed:
    name: Tidy Check Passed
    needs: [check-changed, check-tidy]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - name: All checks passed
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi

