name: Format

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-changed:
    name: Check Changed Files
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-24.04
    outputs:
      any_changed: ${{ steps.check.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v6

      - name: Check relevant files
        id: check
        uses: tj-actions/changed-files@v47.0.1
        with:
          files: |
            include/**
            src/**
            tests/**
            python/**

  check-format:
    name: Check Format
    needs: [check-changed]
    if: ${{ !cancelled() && (needs.check-changed.result == 'skipped' || needs.check-changed.outputs.any_changed == 'true') }}
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v6

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Install Ninja
        run: sudo apt install ninja-build

      - name: Configure
        run: |
          script/configure

      - name: Check format
        run: |
          ninja -C build format
          diff=$(git diff)
          echo -n "$diff"
          test "$(echo -n "$diff" | wc -l) -eq 0"

  format-check-passed:
    name: Format Check Passed
    needs: [check-changed, check-format]
    if: always()
    runs-on: ubuntu-24.04
    steps:
      - name: All checks passed
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi
