name: Build and Test

on:
  push:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "doc/**"
      - "*.md"
  pull_request:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "doc/**"
      - "*.md"

jobs:
  test:
    name: Build and Test
    strategy:
      matrix:
        os: ["linux", "macos"]
        architecture: ["x86_64"]
        device: ["cpu", "cuda"]
        python-version: ["3.10"]
        exclude:
          - os: "macos"
            device: "cuda"
        include:
          - os: "linux"
            architecture: "x86_64"
            runs-on: "ubuntu-22.04"
          - os: "macos"
            architecture: "x86_64"
            runs-on: "macos-13"
    runs-on: ${{ matrix.runs-on }}
    env:
      CMAKE_C_COMPILER_LAUNCHER: "ccache"
      CMAKE_C_COMPILER: ${{ matrix.os == 'macos' && 'gcc-14' || 'gcc' }}
      CMAKE_CXX_COMPILER_LAUNCHER: "ccache"
      CMAKE_CXX_COMPILER: ${{ matrix.os == 'macos' && 'g++-14' || 'g++' }}
      SCALUQ_USE_TEST: "Yes"
      SCALUQ_USE_CUDA: ${{ matrix.device == 'cuda' && 'Yes' || 'No' }}
      SCALUQ_CUDA_ARCH: "PASCAL61"
    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        if: ${{ matrix.os == 'linux' }}
        run: sudo apt update && sudo apt install ninja-build

      - name: Install Ninja
        if: ${{ matrix.os == 'macos' }}
        run: brew install ninja

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: "${{ github.job }}-${{ matrix.device }}"
          verbose: 2

      - name: Install CUDA toolkit
        if: ${{ matrix.device == 'cuda' }}
        uses: Jimver/cuda-toolkit@v0.2.11
        with:
          cuda: "12.2.0"
          method: "network"
      
      - name: Show installed Compiler version
        run: |
          [ SCALUQ_USE_CUDA = 'Yes' ] && nvcc --version
          ccache --version
          $CMAKE_C_COMPILER --version
          $CMAKE_CXX_COMPILER --version
          cmake --version
          ninja --version

      - name: Install scaluq for Ubuntu
        run: CMAKE_BUILD_TYPE=Debug ./script/build_gcc.sh

      - name: Check format
        run: |
          ninja -C build format
          diff=$(git diff)
          echo -n "$diff"
          test $(echo -n "$diff" | wc -l) -eq 0

      - name: Install scaluq Python module
        run: pip install .[ci]

      - name: Test in Ubuntu
        if: ${{ matrix.device == 'cpu' }} # currently GPU runner is not supported
        run: |
          OMP_PROC_BIND=false ninja test -C build -j $(nproc)
      
      - name: Test if stub exists
        run: |
          echo -e "from scaluq import StateVector\nfrom scaluq.gate import I" > /tmp/stub_sample.py
          mypy /tmp/stub_sample.py
