name: Build and Test

on:
  push:
    paths-ignore:
      - ".devcontainer/**"
      - ".vscode/**"
      - "doc/**"
      - "*.md"

jobs:
  test:
    name: Build and Test
    strategy:
      matrix:
        os: ["linux", "macos"]
        architecture: ["x86_64", "arm64"]
        device: ["cpu", "cuda"]
        exclude:
          - os: "macos"
            device: "cuda"
          # currently ARM runner is not supported
          - os: "linux"
            architecture: "arm64"
        include:
          - os: "linux"
            architecture: "x86_64"
            runs-on: "ubuntu-24.04"
          - os: "macos"
            architecture: "x86_64"
            runs-on: "macos-13"
          - os: "macos"
            architecture: "arm64"
            runs-on: "macos-14"
    runs-on: ${{ matrix.runs-on }}
    env:
      CMAKE_C_COMPILER: ${{ matrix.runs-on == 'macos-13' && '/usr/local/opt/ccache/libexec/gcc-14'|| matrix.runs-on == 'macos-14' && '/opt/homebrew/opt/ccache/libexec/gcc-14' || '/usr/lib/ccache/gcc' }}
      CMAKE_CXX_COMPILER: ${{ matrix.runs-on == 'macos-13' && '/usr/local/opt/ccache/libexec/g++-14'|| matrix.runs-on == 'macos-14' && '/opt/homebrew/opt/ccache/libexec/g++-14' || '/usr/lib/ccache/g++' }}
      CMAKE_BUILD_TYPE: ${{ matrix.device == 'cuda' && 'Release' || 'Debug' }}
      SCALUQ_USE_TEST: "ON"
      SCALUQ_USE_CUDA: ${{ matrix.device == 'cuda' && 'ON' || 'OFF' }}
      SCALUQ_CUDA_ARCH: "PASCAL61"
      SCALUQ_FLOAT16: "ON"
      SCALUQ_FLOAT32: "ON"
      SCALUQ_FLOAT64: "ON"
      SCALUQ_BFLOAT16: "ON"
    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        if: ${{ matrix.os == 'linux' }}
        run: sudo apt update && sudo apt install ninja-build

      - name: Install Ninja
        if: ${{ matrix.os == 'macos' }}
        run: brew install ninja

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: "${{ github.job }}-${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.device }}"
          verbose: 2
      
      - name: Install CUDA toolkit
        if: ${{ matrix.device == 'cuda' }}
        uses: Jimver/cuda-toolkit@v0.2.19
        with:
          cuda: "12.6.1"
          method: "network"
      
      - name: Show installed Compiler version
        run: |
          [ $SCALUQ_USE_CUDA = 'ON' ] && nvcc --version
          ccache --version
          $CMAKE_C_COMPILER --version
          $CMAKE_CXX_COMPILER --version
          cmake --version
          ninja --version

      - name: Install Scaluq for Ubuntu
        run: ./script/build_gcc.sh

      - name: Test
        if: ${{ matrix.device == 'cpu' }} # currently GPU runner is not supported
        run: |
          if [ "$(uname)" == 'Darwin' ]; then
            NPROC=$(sysctl -n hw.physicalcpu)
          else
            NPROC=$(nproc)
          fi
          OMP_PROC_BIND=false ctest --test-dir build/ -j ${NPROC}
